/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Membership;

import loginScreen.*;
import UserVerification.LoginVerification;
import java.awt.Color;
import java.text.NumberFormat;
import javax.swing.text.MaskFormatter;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author usman
 */
public class PurchaseForm extends javax.swing.JFrame 
{

    /**
     * Creates new form HomeFrame
     */
    public PurchaseForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderBtn = new javax.swing.JButton();
        numLbl = new javax.swing.JLabel();
        cvvLbl = new javax.swing.JLabel();
        leftPane = new javax.swing.JPanel();
        logoImage = new javax.swing.JLabel();
        mapleLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        monLbl = new javax.swing.JLabel();
        yrLbl = new javax.swing.JLabel();
        monthBox = new javax.swing.JComboBox<>();
        try{
            MaskFormatter formatter = new MaskFormatter("****************");
            formatter.setValidCharacters("0123456789");
            numField = new javax.swing.JFormattedTextField(formatter);
            try{
                MaskFormatter formatter2 = new MaskFormatter("****");
                formatter2.setValidCharacters("0123456789");
                yearField = new javax.swing.JFormattedTextField(formatter2);
                try{
                    MaskFormatter formatter3 = new MaskFormatter("***");
                    formatter3.setValidCharacters("0123456789");
                    cvvField = new javax.swing.JFormattedTextField(formatter3);

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setTitle("MapleView");
                    setBackground(new java.awt.Color(255, 51, 102));
                    setBounds(new java.awt.Rectangle(500, 300, 500, 300));
                    setForeground(java.awt.Color.red);
                    setMinimumSize(new java.awt.Dimension(1000, 555));
                    getContentPane().setLayout(null);

                    orderBtn.setBackground(new java.awt.Color(255, 102, 102));
                    orderBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
                    orderBtn.setForeground(new java.awt.Color(255, 255, 255));
                    orderBtn.setText("Place Order");
                    orderBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            orderBtnActionPerformed(evt);
                            order(evt);
                        }
                    });
                    getContentPane().add(orderBtn);
                    orderBtn.setBounds(560, 260, 150, 36);

                    numLbl.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
                    numLbl.setText("Card Number");
                    getContentPane().add(numLbl);
                    numLbl.setBounds(410, 80, 90, 15);

                    cvvLbl.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
                    cvvLbl.setText("CVV");
                    getContentPane().add(cvvLbl);
                    cvvLbl.setBounds(410, 200, 30, 15);

                    leftPane.setBackground(new java.awt.Color(0, 153, 255));
                    leftPane.setLayout(null);

                    logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-removebg-preview-(1).png"))); // NOI18N
                    leftPane.add(logoImage);
                    logoImage.setBounds(80, 20, 150, 110);

                    mapleLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
                    mapleLabel1.setForeground(new java.awt.Color(255, 255, 255));
                    mapleLabel1.setText("MapleView by MapleTech");
                    leftPane.add(mapleLabel1);
                    mapleLabel1.setBounds(30, 120, 274, 50);

                    jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
                    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-gmail-logo-50.png"))); // NOI18N
                    jLabel1.setText("Contact Support");
                    leftPane.add(jLabel1);
                    jLabel1.setBounds(70, 490, 160, 16);

                    jLabel2.setFont(new java.awt.Font("Montserrat Medium", 2, 18)); // NOI18N
                    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel2.setText("<html>Get Access To Premium Benefits Such As:  5+ Premium Filters, Image Uploading, Exclusives Tools</html>");
                    leftPane.add(jLabel2);
                    jLabel2.setBounds(10, 220, 260, 100);

                    getContentPane().add(leftPane);
                    leftPane.setBounds(0, 0, 310, 520);

                    title.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
                    title.setText("Premium Maple Membership");
                    getContentPane().add(title);
                    title.setBounds(440, 10, 400, 50);

                    errorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                    errorLabel.setForeground(new java.awt.Color(255, 51, 51));
                    getContentPane().add(errorLabel);
                    errorLabel.setBounds(490, 310, 300, 20);
                    errorLabel.setVisible(false);

                    monLbl.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
                    monLbl.setText("Expiry Month");
                    getContentPane().add(monLbl);
                    monLbl.setBounds(410, 140, 90, 15);

                    yrLbl.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
                    yrLbl.setText("Expiry Year");
                    getContentPane().add(yrLbl);
                    yrLbl.setBounds(520, 140, 90, 15);

                    monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
                    getContentPane().add(monthBox);
                    monthBox.setBounds(410, 162, 72, 30);

                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                getContentPane().add(numField);
                numField.setBounds(410, 100, 10, 30);

            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            getContentPane().add(yearField);
            yearField.setBounds(520, 160, 10, 30);

        } catch(Exception e)
        {

        }
        getContentPane().add(cvvField);
        cvvField.setBounds(410, 220, 10, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
          
        String cc = numField.getText();
        String month = monthBox.getSelectedItem().toString();
        String year = yearField.getText();
        String cvv = cvvField.getText();

        String result = Payment.verifyPayment(cc, month, year, cvv);
        //String result = "success";
        if(result.equals("success"))
        {
            String r = UserVerification.User.updateMembership();
            orderBtn.setEnabled(false);
            errorLabel.setText("Payment Successful, You can close this window now!");
            errorLabel.setForeground(Color.GREEN);
            errorLabel.setVisible(true);
            EditorMain.EditorMain.uploadImgBtn.setEnabled(true);
            
        }
        else
        {
            errorLabel.setText(result);
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_orderBtnActionPerformed

    private void order(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order
        // TODO add your handling code here:
    }//GEN-LAST:event_order

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cvvField;
    private javax.swing.JLabel cvvLbl;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftPane;
    private javax.swing.JLabel logoImage;
    private javax.swing.JLabel mapleLabel1;
    private javax.swing.JLabel monLbl;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JFormattedTextField numField;
    private javax.swing.JLabel numLbl;
    private static javax.swing.JButton orderBtn;
    private javax.swing.JLabel title;
    private javax.swing.JFormattedTextField yearField;
    private javax.swing.JLabel yrLbl;
    // End of variables declaration//GEN-END:variables
}
