/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SocialGallery;

/**
 *
 * @author usman
 */
public class socialWallFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form socialWallFrame
     */
    public socialWallFrame1() {
        initComponents();
        //setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        postPictureButton = new javax.swing.JButton();
        editorButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        editorButton2 = new javax.swing.JButton();
        editorButton3 = new javax.swing.JButton();
        editorButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        editorButton4 = new javax.swing.JButton();
        editorButton5 = new javax.swing.JButton();
        editorButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(397, 511));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logostyle2.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        postPictureButton.setBackground(new java.awt.Color(51, 102, 255));
        postPictureButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        postPictureButton.setForeground(new java.awt.Color(255, 255, 255));
        postPictureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-post-stamp-25.png"))); // NOI18N
        postPictureButton.setText("Make a Post");
        postPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postPictureButtonActionPerformed(evt);
            }
        });
        jPanel1.add(postPictureButton, java.awt.BorderLayout.LINE_START);

        editorButton1.setBackground(new java.awt.Color(255, 102, 102));
        editorButton1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        editorButton1.setForeground(new java.awt.Color(255, 255, 255));
        editorButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-image-25.png"))); // NOI18N
        editorButton1.setText("Go to Editor");
        jPanel1.add(editorButton1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel2.setText("@postedBy");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        editorButton2.setBackground(new java.awt.Color(51, 153, 255));
        editorButton2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        editorButton2.setForeground(new java.awt.Color(255, 255, 255));
        editorButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-chat-room-25.png"))); // NOI18N
        editorButton2.setText("Comment");
        editorButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButton2ActionPerformed(evt);
            }
        });

        editorButton3.setBackground(new java.awt.Color(255, 204, 0));
        editorButton3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        editorButton3.setForeground(new java.awt.Color(255, 255, 255));
        editorButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-share-25.png"))); // NOI18N
        editorButton3.setText("Share");
        editorButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButton3ActionPerformed(evt);
            }
        });

        editorButton.setBackground(new java.awt.Color(255, 102, 102));
        editorButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        editorButton.setForeground(new java.awt.Color(255, 255, 255));
        editorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-heart-25.png"))); // NOI18N
        editorButton.setText("Like");
        editorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(editorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editorButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editorButton3))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorButton)
                    .addComponent(editorButton3)
                    .addComponent(editorButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel3.setText("@postedBy");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        editorButton4.setBackground(new java.awt.Color(51, 153, 255));
        editorButton4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        editorButton4.setForeground(new java.awt.Color(255, 255, 255));
        editorButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-chat-room-25.png"))); // NOI18N
        editorButton4.setText("Comment");
        editorButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButton4ActionPerformed(evt);
            }
        });

        editorButton5.setBackground(new java.awt.Color(255, 204, 0));
        editorButton5.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        editorButton5.setForeground(new java.awt.Color(255, 255, 255));
        editorButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-share-25.png"))); // NOI18N
        editorButton5.setText("Share");
        editorButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButton5ActionPerformed(evt);
            }
        });

        editorButton6.setBackground(new java.awt.Color(255, 102, 102));
        editorButton6.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        editorButton6.setForeground(new java.awt.Color(255, 255, 255));
        editorButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-heart-25.png"))); // NOI18N
        editorButton6.setText("Like");
        editorButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(editorButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editorButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editorButton5))
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorButton6)
                    .addComponent(editorButton5)
                    .addComponent(editorButton4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jScrollBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postPictureButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postPictureButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void editorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorButtonActionPerformed

    private void editorButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorButton2ActionPerformed

    private void editorButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void editorButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorButton4ActionPerformed

    private void editorButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorButton5ActionPerformed

    private void editorButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(socialWallFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(socialWallFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(socialWallFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(socialWallFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new socialWallFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editorButton;
    private javax.swing.JButton editorButton1;
    private javax.swing.JButton editorButton2;
    private javax.swing.JButton editorButton3;
    private javax.swing.JButton editorButton4;
    private javax.swing.JButton editorButton5;
    private javax.swing.JButton editorButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton postPictureButton;
    // End of variables declaration//GEN-END:variables
}
