/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginScreen;

import UserVerification.ForgotPassword;
import UserVerification.LoginVerification;

/**
 *
 * @author usman
 */
public class ForgotPassFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public ForgotPassFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpButton = new javax.swing.JButton();
        signUpNowLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        leftPane = new javax.swing.JPanel();
        logoImage = new javax.swing.JLabel();
        mapleLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        forgotPassBtn = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        successLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MapleView");
        setBackground(new java.awt.Color(255, 51, 102));
        setBounds(new java.awt.Rectangle(500, 300, 500, 300));
        setForeground(java.awt.Color.red);
        setMinimumSize(new java.awt.Dimension(1000, 555));
        getContentPane().setLayout(null);

        signUpButton.setBackground(new java.awt.Color(0, 102, 255));
        signUpButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-male-50.png"))); // NOI18N
        signUpButton.setText("Sign Up Now!");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton);
        signUpButton.setBounds(560, 370, 170, 36);

        signUpNowLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        signUpNowLabel.setText("Don't Have an Account?");
        getContentPane().add(signUpNowLabel);
        signUpNowLabel.setBounds(570, 350, 159, 15);

        emailLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        emailLabel.setText("Enter Registered Mail");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(460, 150, 130, 15);

        emailField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(460, 170, 353, 30);

        leftPane.setBackground(new java.awt.Color(0, 153, 255));
        leftPane.setLayout(null);

        logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-removebg-preview-(1).png"))); // NOI18N
        leftPane.add(logoImage);
        logoImage.setBounds(80, 20, 150, 110);

        mapleLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        mapleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        mapleLabel1.setText("MapleView by MapleTech");
        leftPane.add(mapleLabel1);
        mapleLabel1.setBounds(30, 120, 274, 50);

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-gmail-logo-50.png"))); // NOI18N
        jLabel1.setText("Contact Support");
        leftPane.add(jLabel1);
        jLabel1.setBounds(70, 490, 160, 16);

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>An image editor with a place to edit & share art with your loved onlines!</html>");
        leftPane.add(jLabel2);
        jLabel2.setBounds(10, 220, 320, 100);

        getContentPane().add(leftPane);
        leftPane.setBounds(0, 0, 310, 520);

        label2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        label2.setText("Don't Worry We Got You!");
        getContentPane().add(label2);
        label2.setBounds(480, 80, 340, 50);

        errorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(errorLabel);
        errorLabel.setBounds(590, 210, 260, 30);
        errorLabel.setVisible(false);

        forgotPassBtn.setBackground(new java.awt.Color(255, 153, 0));
        forgotPassBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        forgotPassBtn.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassBtn.setText("Recover Password");
        forgotPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassBtnActionPerformed(evt);
            }
        });
        getContentPane().add(forgotPassBtn);
        forgotPassBtn.setBounds(560, 300, 170, 30);

        label1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        label1.setText("Forgot Your Password?");
        getContentPane().add(label1);
        label1.setBounds(490, 40, 320, 50);

        successLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        successLbl.setForeground(new java.awt.Color(0, 204, 0));
        successLbl.setVisible(false);
        getContentPane().add(successLbl);
        successLbl.setBounds(480, 240, 400, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        this.dispose();
        new SignUpFrame().setVisible(true);
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void forgotPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassBtnActionPerformed
        String email = emailField.getText();
        String result = ForgotPassword.forgotPass(email);
        if(result.equals("success") || result.equals("notexist")){
            successLbl.setText("Password send on mail if it exists!\n Make sure to check spam ");
            successLbl.setVisible(true);
        }
        else
        {
            errorLabel.setText(result);
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_forgotPassBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton forgotPassBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JPanel leftPane;
    private javax.swing.JLabel logoImage;
    private javax.swing.JLabel mapleLabel1;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel signUpNowLabel;
    private javax.swing.JLabel successLbl;
    // End of variables declaration//GEN-END:variables
}
